name: DynamicTextarea
author: Amadeus Demarzi
category: Forms
tags: [class, textarea, dynamic, input]
docs: http://enmassellc.com/misc/dynamicTextarea.html
demo: http://enmassellc.com/misc/dynamicTextarea.html